# Based on:
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
# https://docs.docker.com/build/ci/github-actions/manage-tags-labels/

on:
  pull_request:
    branches:
    - main
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v4      
      - if: github.event_name == 'pull_request'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

          # https://github.com/docker/metadata-action?tab=readme-ov-file#tags-input
          tags: |
            type=ref,event=branch
            type=sha  

      - if: github.event_name == 'pull_request'
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - if: github.event_name == 'pull_request'
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      # Automatically deploy by updating the image tag in dev repo.
      # This requires a personal token with "Contents" read and write permission.
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          repository: 'evanstucker-hates-2fa/dev-k8s'
          token: ${{ secrets.DEPLOY_PAT }}
      - if: github.event_name == 'pull_request'
        name: Updating image tag in dev repo
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update && apt install -y --no-install-recommends curl
          curl -sL -o /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64" && chmod +x /usr/local/bin/yq
          yq -i ".image.tag = \"sha-${GITHUB_SHA::7}\"" test-app.helm_values.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Updating test-app image tag"
          git push

      # Automatically deploy by updating the image tag in prod repo.
      # This requires a personal token with "Contents" read and write permission.
      - if: github.ref == 'refs/heads/main' 
        uses: actions/checkout@v4
        with:
          repository: 'evanstucker-hates-2fa/prod-k8s'
          token: ${{ secrets.DEPLOY_PAT }}
      - if: github.ref == 'refs/heads/main'
        name: Updating image tag in prod repo
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update && apt install -y --no-install-recommends curl
          curl -sL -o /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64" && chmod +x /usr/local/bin/yq
          yq -i ".image.tag = \"sha-${GITHUB_SHA::7}\"" test-app.helm_values.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Updating test-app image tag"
          git push
