# Based on:
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
# https://docs.docker.com/build/ci/github-actions/manage-tags-labels/

on:
  pull_request:
    branches:
    - main
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v4      
      - if: github.event_name == 'pull_request'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

          # https://github.com/docker/metadata-action?tab=readme-ov-file#tags-input
          tags: |
            type=ref,event=branch
            type=sha  

      - if: github.event_name == 'pull_request'
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # TODO: Fix this so that it only retags on push to main branch without rebuilding the image.
      #- uses: docker/build-push-action@v6
      #  if: github.ref == 'refs/heads/main'
      #  with:
      #    context: .
      #    push: true
      #    tags: ${{ steps.meta.outputs.tags }}
      #    labels: ${{ steps.meta.outputs.labels }}

      - uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      # Automatically deploy by updating the image tag in dev repo.
      # This requires a personal token with "Contents" read and write permission.
      - uses: actions/checkout@v4
        with:
          repository: 'evanstucker-hates-2fa/dev-k8s'
          token: ${{ secrets.DEPLOY_PAT }}
      - name: Deploy new image to https://beta.prod.nebra.one/
        run: |
          YQ_VERSION=v4.44.3
          curl -sL -o /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64" && chmod +x /usr/local/bin/yq
          yq -i ".image.tag = \"sha-${GITHUB_SHA::7}\"" helm/beta-website.helm_values.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Deploying beta-website"
          git push